### ISSUE TITLE
Requirejs / AMD support?

### ISSUE THREAD

**Issue by andrewboni** [remotty/angular-ladda#10]
Using `angular-ladda` with requirejs leads to an issue:

```
ReferenceError: Ladda is not defined
```
...since Ladda is no longer defined on the global scope. Any way to resolve this? Thanks!

**Comment by subicura** [comment]
Do you include ladda.js? And can you show me sample code for this issue?

**Comment by andrewboni** [comment]
Yes, `ladda.js` is included on the page.

In `app.js` I have listed `angular-ladda` as a module dependency. In `app.js` I do a `console.log("Ladda is", Ladda)` and it's there:
![screenshot 2015-01-08 16 17 21](https://cloud.githubusercontent.com/assets/255026/5673531/092dfe5a-9752-11e4-9228-7deeed9b8e5f.png)

`angular-ladda` just isn't able to find it because it's no longer part of the global scope, since requirejs doesn't expose things globally.

**Comment by subicura** [comment]
OK. This is requirejs issue, right?
I don't know about requirejs very well. But I'll check this soon!

**Comment by andrewboni** [comment]
Yes, this is using angular-ladda in conjunction with requirejs

**Comment by thetutlage** [comment]
Require js follows AMD pattern to load modules. Check this pull request i have fixed it , waiting for the guy to review

https://github.com/remotty/angular-ladda/pull/18

**Comment by subicura** [comment]
@thetutlage Thanks :)

**Comment by soundslocke** [comment]
This is still a problem. After loading angular-ladda the global Ladda object is destroyed/reassigned to undefined. This causes any other JavaScript which uses Ladda to break.

A simple example: include angular-ladda on a page and then use vanilla JS to bind/stop Ladda instances. See: http://jsfiddle.net/saaq6qqr/
